### ISSUE TITLE
Error with UTF-8

### ISSUE THREAD

**Issue by dongbum** [yulrizka/redmine2github#3]
When I use redmine2github converter, I see this error message.
(My guess is because of file include Korean characters.)

```
[root@localhost redmine2github-master]# ruby redmine2github.rb USERNAME PROJECTNAME issues.csv -u users.yml -e blahblahblah,http://my.redmine-site.com -m -v
Github username: iamgituser
Github password: **********
Authenticating...
/usr/share/ruby/csv.rb:1987:in `=~': invalid byte sequence in UTF-8 (ArgumentError)
        from /usr/share/ruby/csv.rb:1987:in `init_separators'
        from /usr/share/ruby/csv.rb:1509:in `initialize'
        from /usr/share/ruby/csv.rb:1261:in `new'
        from /usr/share/ruby/csv.rb:1261:in `open'
        from /usr/share/ruby/csv.rb:1119:in `foreach'
        from redmine2github.rb:95:in `<main>'
[root@localhost redmine2github-master]#
```

**Comment by dongbum** [comment]
After issue.csv file was save as UTF-8 (Not include BOM), it works.
I wish code update for non-English country user.
